zookeeper:
  image: benxing/zookeeper:0.1
  ports:
     - "2181:2181"
     - "2888:2888"
     - "3888:3888"


kafka1:
  image: benxing/kafka:0.9
  ports: 
     - "9092:9092"
  links:
     - zookeeper:zk
  environment:
     KAFKA_ADVERTISED_HOST_NAME: 192.168.1.22
     KAFKA_BROKER_ID: 1
  volumes:
     - /var/run/docker.sock:/var/run/docker.sock

kafka2:
  image: benxing/kafka:0.9
  ports:
     - "9093:9092"
  links:
     - zookeeper:zk
  environment:
     KAFKA_ADVERTISED_HOST_NAME: 192.168.1.22
     KAFKA_BROKER_ID: 2
  volumes:
     - /var/run/docker.sock:/var/run/docker.sock

kafka3:
  image: benxing/kafka:0.9
  ports:
     - "9094:9092"
  links:
     - zookeeper:zk
  environment:
     KAFKA_ADVERTISED_HOST_NAME: 192.168.1.22
     KAFKA_BROKER_ID: 3
  volumes:
     - /var/run/docker.sock:/var/run/docker.sock


  
